# Generated by Django 3.0.3 on 2020-03-06 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='password',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
